theme: jekyll-theme-cayman

# Setup
title: Laravel File Manager
description: File manager/gallery with CKEditor and TinyMCE support.

# About/contact
author:
  name: Jeylabs
  url: https://github.com/jeylabs
